import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{LayoutDashboard,Users,GitBranch,Receipt,Wallet,BarChart3,Package,ShoppingCart,Settings,ShieldCheck,LogOut,Menu,X,Bell,Search,ChevronRight}from"lucide-react";
import"./style.css";import"./vora-theme.css";
import{supabase}from"./supabase";
import{VoraMembers,VoraNetwork,VoraOrders,VoraWallet,VoraRewards}from"./vora-modules";

const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const num=n=>new Intl.NumberFormat("id-ID").format(Number(n)||0);

function Login({onLogin}){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const submit=async e=>{e.preventDefault();setBusy(true);setError("");const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false);if(!error)onLogin()};
 return <div className="vora-login"><div className="vora-login-card"><div className="vora-logo"><img src="/vora-icon.svg"/><div><b>VORA</b><small>Digital Business Ecosystem</small></div></div><h1>Selamat datang di VORA</h1><p>Kelola bisnis, network, transaksi, reward, dan wallet dari satu ekosistem.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{error&&<div className="login-error">{error}</div>}<button className="primary" disabled={busy}>{busy?"Memproses…":"Masuk ke VORA"}</button></form><small className="login-note">Akun menggunakan Supabase Auth. Tidak ada password yang disimpan oleh UI VORA.</small></div></div>
}

function Dashboard({cloud,setPage}){
 const[stats,setStats]=useState({members:0,orders:0,gmv:0,qualified:0});
 useEffect(()=>{(async()=>{if(!cloud.businessId)return;const [m,o]=await Promise.all([supabase.from("vora_members").select("id,status",{count:"exact"}).eq("business_id",cloud.businessId),supabase.from("vora_orders").select("total,qualified_amount").eq("business_id",cloud.businessId).limit(1000)]);const rows=o.data||[];setStats({members:m.count||0,orders:rows.length,gmv:rows.reduce((a,x)=>a+Number(x.total||0),0),qualified:rows.reduce((a,x)=>a+Number(x.qualified_amount||0),0)})})()},[cloud.businessId]);
 return <><div className="pageHead"><div><span className="eyebrow">VORA • EXECUTIVE CONTROL</span><h1>Dashboard VORA</h1><p>Pusat kendali ekosistem bisnis digital Anda.</p></div><button className="primary" onClick={()=>setPage("VORA Orders")}><ShoppingCart size={16}/> Buka Commerce</button></div><section className="hero"><div><span>DIGITAL BUSINESS ECOSYSTEM</span><strong>Momentum Menuju Perkembangan</strong><small><ShieldCheck size={13}/> Pertumbuhan berbasis transaksi nyata & transparansi</small></div><div className="heroChart"><span/><span/><span/><span/><span/><span/><span/></div></section><div className="metricGrid"><Metric icon={Users} label="Members" value={num(stats.members)} note="Jaringan terdaftar"/><Metric icon={Receipt} label="Orders" value={num(stats.orders)} note="Transaksi cloud"/><Metric icon={Wallet} label="GMV" value={money(stats.gmv)} note="Nilai transaksi"/><Metric icon={BarChart3} label="Qualified" value={money(stats.qualified)} note="Basis reward"/></div><div className="reportGrid"><section className="panel"><PanelHead title="Prinsip VORA" sub="Fondasi sistem"><div className="vora-principles"><p><b>01</b> Reward berasal dari aktivitas bisnis yang memenuhi syarat.</p><p><b>02</b> Ledger finansial immutable dan koreksi menggunakan reversal.</p><p><b>03</b> RLS membatasi data berdasarkan bisnis dan peran.</p><p><b>04</b> Semua aksi finansial penting meninggalkan audit trail.</p></div></PanelHead></section><section className="panel"><PanelHead title="Modul Inti" sub="Roadmap aktif"><div className="module-grid"><button onClick={()=>setPage("VORA Members")}><Users/><span>Members</span></button><button onClick={()=>setPage("VORA Network")}><GitBranch/><span>Network</span></button><button onClick={()=>setPage("VORA Orders")}><Receipt/><span>Commerce</span></button><button onClick={()=>setPage("VORA Wallet")}><Wallet/><span>Wallet</span></button></div></PanelHead></section></div></>
}
const Metric=({icon:I,label,value,note})=><div className="metric"><div className="metricIcon"><I size={18}/></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>;
const PanelHead=({title,sub,children})=><div className="panelHead"><div><h2>{title}</h2><small>{sub}</small></div>{children}</div>;

function App(){
 const[session,setSession]=useState(null),[cloud,setCloud]=useState({businessId:null,userId:null}),[page,setPage]=useState("Dashboard"),[mobile,setMobile]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase){setLoading(false);return}let mounted=true;(async()=>{const{data}=await supabase.auth.getSession();if(mounted){setSession(data.session);setLoading(false)}})();const{data:sub}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)setLoading(false)});return()=>{mounted=false;sub.subscription.unsubscribe()};},[]);
 useEffect(()=>{(async()=>{if(!session?.user?.id)return;const{data:m}=await supabase.from("memberships").select("business_id").eq("user_id",session.user.id).limit(1).maybeSingle();if(m?.business_id)setCloud({businessId:m.business_id,userId:session.user.id})})()},[session?.user?.id]);
 if(loading)return <div className="vora-loading">Memuat VORA…</div>;
 if(!supabase)return <div className="vora-login"><div className="vora-login-card"><div className="vora-logo"><img src="/vora-icon.svg"/><div><b>VORA</b><small>Digital Business Ecosystem</small></div></div><h1>Cloud belum dikonfigurasi</h1><p>Isi VITE_SUPABASE_URL dan VITE_SUPABASE_ANON_KEY sebelum VORA dijalankan.</p></div></div>;
 if(!session)return <Login onLogin={()=>{}}/>;
 const nav=[["Dashboard",LayoutDashboard],["VORA Members",Users],["VORA Network",GitBranch],["VORA Orders",Receipt],["VORA Wallet",Wallet],["VORA Rewards",BarChart3],["Produk",Package],["Kasir",ShoppingCart],["Pengaturan",Settings]];
 const pageMap={Dashboard:<Dashboard cloud={cloud} setPage={setPage}/>, "VORA Members":<VoraMembers cloud={cloud}/>, "VORA Network":<VoraNetwork cloud={cloud}/>, "VORA Orders":<VoraOrders cloud={cloud}/>, "VORA Wallet":<VoraWallet cloud={cloud}/>, "VORA Rewards":<VoraRewards cloud={cloud}/>, "Produk":<LegacyNotice title="Produk" text="Mesin katalog dan inventory VORA akan memakai product engine yang sudah ada di fondasi POS."/>,"Kasir":<LegacyNotice title="Commerce / Kasir" text="Checkout atomic dari fondasi POS tetap dipertahankan dan akan dihubungkan ke VORA Orders."/>,"Pengaturan":<LegacyNotice title="Pengaturan" text="RBAC, bisnis, outlet, keamanan, notifikasi, dan payment settings akan ditempatkan di sini."/>};
 return <div className="app"><header className="header"><div className="brand"><div className="brandIcon"><img src="/vora-icon.svg"/></div><div><b>VORA</b><small>Digital Business Ecosystem</small></div></div><div className="headerRight"><span className="status"><i/> Online</span><button className="iconBtn"><Bell size={18}/></button><div className="avatar">V</div><div className="userName"><b>VORA Member</b><small>{session.user.email}</small></div><button className="iconBtn" title="Keluar" onClick={()=>supabase.auth.signOut()}><LogOut size={17}/></button></div><button className="menuBtn" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header><aside className={mobile?"open":""}><div><div className="outlet"><div className="outletMark">V</div><div><b>VORA Ecosystem</b><small>{cloud.businessId?"Business connected":"Business belum terhubung"}</small></div><ChevronRight size={16}/></div><nav>{nav.map(([n,I])=><button className={page===n?"active":""} onClick={()=>{setPage(n);setMobile(false)}} key={n}><I size={18}/><span>{n}</span></button>)}</nav></div><div className="sideFoot"><div className="cloud"><ShieldCheck size={16}/><span><b>Security Layer</b><small>Supabase Auth + RLS</small></span><i/></div><small>VORA Foundation 0.1</small></div></aside><main>{pageMap[page]}</main></div>
}
function LegacyNotice({title,text}){return <><div className="pageHead"><div><span className="eyebrow">VORA • MODULE</span><h1>{title}</h1><p>{text}</p></div></div><section className="panel"><div className="empty"><ShieldCheck size={30}/><b>Fondasi siap diintegrasikan</b><span>Modul ini sengaja dipisahkan agar tidak memutus engine POS yang sudah ada.</span></div></section></>}
createRoot(document.getElementById("root")).render(<App/>);
